# Chap.4 numpy套件(numeric python)
## 為什麼需要numpy?
* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [ ]:
a_list=[1,2,3,4,5] #a_list包含1,2,3,4,5
print(a_list*3) #顯示a_list三次

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np #import語句用来導入其他python文件
a=np.array([1,2,3,4,5]) 
print(a*3) #顯示將a的所有元素都乘三倍

[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,5])
print(type(a)) #顯示a的資料型態
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int32
1


In [ ]:
import numpy as np
z=np.zeros(6) #在z中生成6個0
print(z) #顯示z
print(np.empty((2,3,4))) #快速創建ndarray類组，可以使用numpy.empty()函數，創建的類组内所有元素均為空
print(np.arange(10)) #arange均勻間隔值的數組

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


## ndarray的進階操作

In [ ]:
my_array=np.arange(10) #arange均勻間隔值的數組
print(my_array) #顯示my_array
print(my_array[0]) #顯示my_array第0個
print(my_array[0:5]) #顯示my_array範圍0到第5個

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


### 2維資料取值

In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array) #顯示my_2d_array
print(my_2d_array[1,:]) 
print(my_2d_array[:,1]) 
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [ ]:
my_array=np.arange(0,10) #arange均勻間隔值的數組
print(my_array)  #顯示my_array
print(my_array.shape) #shape的功能是讀取矩陣的長度，顯示my_array的長度
my_2d_array=my_array.reshape(2,5)  #reshape(行數，列數)常用來更改數據的行列數目
print(my_2d_array) #顯示my_2d_array
print((np.arange(0,100).reshape(10,10)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### numpy的空值nan

In [ ]:
b=np.array([56, 8, 19, 14, np.nan])
print(b) #顯示b

[56.  8. 19. 14. nan]
